pipeline {
    agent any

    stages {

        stage('Setup Environment') {
            steps {
                dir('loginpage') {
                    bat 'npm install'
                }
            }
        }

        stage('Build & Deploy') {
            steps {
                dir('loginpage') {
                    bat 'docker-compose down || exit 0'
                    bat 'docker-compose up -d --build'
                }
            }
        }

        stage('Health Check') {
            steps {
                dir('loginpage') {
                    bat 'ping 127.0.0.1 -n 11 > nul'
                    bat 'curl -f http://localhost:3000/health || exit 1'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
